### ISSUE TITLE
I am unable to run podium.

### ISSUE THREAD

**Issue by RatanShreshtha** [pybee/podium#12] opened 2017-10-18 09:48 UTC
I am trying  to run podium in my machine as suggested in docs, first I tried using running podium then I get `import error` for `gi` then I enabled site-packages in my virtual environment then I get error regarding **Rubicon** then I installed rubicon in virtual environment but now I am getting following error

```
Traceback (most recent call last):
  File "/home/ratan/.local/share/virtualenvs/podium-oIEB1OXF/bin/podium", line 11, in <module>
    load_entry_point('podium', 'console_scripts', 'podium')()
  File "/home/ratan/.local/share/virtualenvs/podium-oIEB1OXF/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ratan/.local/share/virtualenvs/podium-oIEB1OXF/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/home/ratan/.local/share/virtualenvs/podium-oIEB1OXF/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/home/ratan/.local/share/virtualenvs/podium-oIEB1OXF/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ratan/Desktop/foss/podium/podium/__main__.py", line 1, in <module>
    from podium.app import main
  File "/home/ratan/Desktop/foss/podium/podium/app.py", line 5, in <module>
    from podium.deck import *
  File "/home/ratan/Desktop/foss/podium/podium/deck.py", line 3, in <module>
    from rubicon.objc import ObjCClass, objc_classmethod, objc_method
  File "/home/ratan/.local/share/virtualenvs/podium-oIEB1OXF/lib/python3.6/site-packages/rubicon/objc/__init__.py", line 3, in <module>
    from .objc import (
  File "/home/ratan/.local/share/virtualenvs/podium-oIEB1OXF/lib/python3.6/site-packages/rubicon/objc/objc.py", line 49, in <module>
    objc = _load_or_error('objc')
  File "/home/ratan/.local/share/virtualenvs/podium-oIEB1OXF/lib/python3.6/site-packages/rubicon/objc/objc.py", line 46, in _load_or_error
    raise ValueError("Library {!r} not found".format(name))
ValueError: Library 'objc' not found
```

I am using fedora 26 with 4.13.5-200.fc26.x86_64 kernel, python 3.6.

**Comment by freakboy3742** [comment] 2017-10-18 23:24
Thanks for the report! Unfortunately, Podium is need of some attention at the moment; I've been using a local build that works, but haven't migrated those changes into the main repository. This is all on my (very long) todo list...

**Comment by RatanShreshtha** [comment] 2017-10-19 06:44
I would like to contribute if there is any thing I can help with.

**Comment by freakboy3742** [comment] 2018-08-04 04:00
If you're on Fedora, this is an effective duplicate of #11; Podium currently uses APIs that aren't cross-platform. This is something we want to a address; if you want to help out, getting the "full screen" API working for GTK would be the first step.

**Closed by freakboy3742** 2018-08-04 04:00 UTC
